; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ch32v
framework = ch32v003fun
monitor_speed = 115200
;upload_protocol = wlink

[env:genericCH32V003F4U6]
board = genericCH32V003F4U6
; prevent ch32fun from recognizing the wrong chip series
; not needed anymore in latest ch32v platform versions, left for reference.
;build_unflags = -DCH32V00x
lib_deps = https://github.com/maxgerhardt/rv003usb.git#136e2d107c6c8c08c52acd5ae24e93e5b4af0a15
extra_scripts =
  ; convenience for showing USB descriptors in intellisense
  pre:$PROJECT_LIBDEPS_DIR/$PIOENV/rv003usb/.github/show_descriptors.py
