; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericCH32H417QEU6_V3F, genericCH32H417QEU6_V5F

[env]
platform = ch32v
framework = noneos-sdk
monitor_speed = 115200
; uncomment this to use USB bootloader upload via WCHISP
;upload_protocol = isp
;upload_protocol = wlink

; BOTH FIRMWARES MUST BE UPLOADED
; The V3F firmware waits for the V5F to wake up.
; Use the "Default" environment in the project environment switcher
; And use the project task "Upload All" for easy upload.

[env:genericCH32H417QEU6_V3F]
board = genericCH32H417QEU6_V3F

[env:genericCH32H417QEU6_V5F]
board = genericCH32H417QEU6_V5F
